"use client";

import { useMemo, useState } from "react";
import { Download, Search, SlidersHorizontal, ArrowUpRight, ArrowDownLeft, ShieldAlert, ChevronRight, Check, Moon, Sun, Activity, Clock3, LockKeyhole } from "lucide-react";
import FinverseLink from "@/components/FinverseLink";

type WorkspaceView = "dashboard" | "accounts" | "transfers" | "insights" | "statements" | "notifications" | "settings" | "operations" | "admin";

type LedgerWorkspaceProps = {
  view: WorkspaceView;
  user: User;
  accounts?: Account[];
  transactions?: Transaction[];
};

type LedgerTransaction = Transaction & { merchant: string; day: string; recurring?: boolean; flagged?: string };

const fallbackAccounts: Account[] = [
  { id: "demo-checking", appwriteItemId: "demo-checking", availableBalance: 12840.76, currentBalance: 12840.76, institutionId: "demo-bank", name: "Everyday Checking", officialName: "Nexa Demo Checking", mask: "1024", type: "depository", subtype: "checking", sharableId: "checking" },
  { id: "demo-savings", appwriteItemId: "demo-savings", availableBalance: 45280.19, currentBalance: 45280.19, institutionId: "demo-bank", name: "Reserve Savings", officialName: "Nexa Demo Savings", mask: "8891", type: "depository", subtype: "savings", sharableId: "savings" },
];

const seedTransactions: LedgerTransaction[] = [
  { id: "demo-tx-1", merchant: "Payroll Deposit", name: "Payroll Deposit", amount: 3250, date: "2026-09-16", day: "Wed", paymentChannel: "online", category: "Income", type: "credit", accountId: "demo-checking", recurring: true },
  { id: "demo-tx-2", merchant: "Coffee House", name: "Coffee House", amount: 12.4, date: "2026-09-14", day: "Mon", paymentChannel: "online", category: "Food & Drink", type: "debit", accountId: "demo-checking" },
  { id: "demo-tx-3", merchant: "Transfer to Savings", name: "Transfer to Savings", amount: 800, date: "2026-09-11", day: "Fri", paymentChannel: "online", category: "Transfer", type: "debit", accountId: "demo-checking", recurring: true },
  { id: "demo-tx-4", merchant: "Apartment Rent", name: "Apartment Rent", amount: 1750, date: "2026-09-06", day: "Sun", paymentChannel: "online", category: "Housing", type: "debit", accountId: "demo-checking", recurring: true, flagged: "3x median transaction size" },
  { id: "demo-tx-5", merchant: "Groceries", name: "Groceries", amount: 146.2, date: "2026-09-04", day: "Fri", paymentChannel: "online", category: "Food & Drink", type: "debit", accountId: "demo-checking" },
  { id: "demo-tx-6", merchant: "Cloud Services", name: "Cloud Services", amount: 39, date: "2026-09-02", day: "Wed", paymentChannel: "online", category: "Subscriptions", type: "debit", accountId: "demo-checking", recurring: true },
  { id: "demo-tx-7", merchant: "Railway Market", name: "Railway Market", amount: 84.5, date: "2026-08-30", day: "Sat", paymentChannel: "online", category: "Food & Drink", type: "debit", accountId: "demo-savings", flagged: "first-time payee" },
];

const nav: Array<{ label: string; view: WorkspaceView }> = [
  { label: "Overview", view: "dashboard" }, { label: "Accounts", view: "accounts" }, { label: "Transfers", view: "transfers" }, { label: "Insights", view: "insights" },
  { label: "Statements", view: "statements" }, { label: "Notifications", view: "notifications" }, { label: "Settings", view: "settings" },
];

function Money({ value, className = "" }: { value: number; className?: string }) {
  return <span className={`tabular-nums ${className}`}>{value < 0 ? "−" : ""}${Math.abs(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>;
}

function SectionTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) {
  return <header className="ledger-section-title"><div><p className="ledger-eyebrow">{eyebrow}</p><h1>{title}</h1>{detail && <p className="ledger-muted mt-2">{detail}</p>}</div></header>;
}

function ForecastChart({ adjustment = 0 }: { adjustment?: number }) {
  const actual = [42, 48, 44, 58, 54, 61, 59, 68, 64, 72, 70, 78];
  const projected = [78, 75, 80 - adjustment / 20, 73 - adjustment / 15, 76 - adjustment / 12, 68 - adjustment / 10];
  return <div className="ledger-chart" aria-label="Cash flow forecast chart"><svg viewBox="0 0 640 220" role="img"><path d="M0 180 H640" className="chart-grid" /><path d="M0 120 H640" className="chart-grid" /><path d="M0 60 H640" className="chart-grid" /><polyline points={actual.map((v, i) => `${i * 52},${190 - v * 1.55}`).join(" ")} className="chart-actual" /><polyline points={projected.map((v, i) => `${572 + i * 14},${190 - v * 1.55}`).join(" ")} className="chart-projected" /><line x1="572" y1="15" x2="572" y2="190" className="chart-today" /></svg><div className="chart-legend"><span><i className="legend-line actual" /> Actual history</span><span><i className="legend-line projected" /> Projected</span><span className="ledger-muted">Today</span></div></div>;
}

function CategoryDonut() {
  return <div className="donut-wrap"><div className="donut" /><div><div className="donut-total"><span>$2,748</span><small>this month</small></div><div className="donut-key"><span><i className="key-dot forest" />Housing <b>64%</b></span><span><i className="key-dot amber" />Food & Drink <b>18%</b></span><span><i className="key-dot navy" />Other <b>18%</b></span></div></div></div>;
}

function ActivityList({ transactions }: { transactions: LedgerTransaction[] }) {
  return <div className="ledger-list">{transactions.slice(0, 5).map((transaction) => <div className="ledger-list-row" key={transaction.id}><div className={`activity-icon ${transaction.type === "credit" ? "credit" : "debit"}`}>{transaction.type === "credit" ? <ArrowDownLeft size={16} /> : <ArrowUpRight size={16} />}</div><div className="min-w-0 flex-1"><p className="font-semibold truncate">{transaction.merchant}</p><p className="ledger-muted text-xs">{transaction.category} · {transaction.date}</p></div><Money value={transaction.type === "credit" ? transaction.amount : -transaction.amount} className={transaction.type === "credit" ? "ledger-positive" : ""} /></div>)}</div>;
}

function ConnectBankState({ user }: { user: User }) {
  return <div className="ledger-connect-state"><div className="ledger-connect-mark"><Activity size={24} /></div><p className="ledger-eyebrow">Actual banking mode</p><h2>Connect your first bank</h2><p className="ledger-muted">Your real account balances and transactions will appear here after you authorize a supported financial institution.</p><FinverseLink user={user} variant="primary" /><small className="ledger-muted">Secure connection · provider availability varies by institution</small></div>;
}

function Dashboard({ accounts, transactions, user }: { accounts: Account[]; transactions: LedgerTransaction[]; user: User }) {
  if (user.mode === "actual" && accounts.length === 0) {
    return <div className="ledger-page"><SectionTitle eyebrow="Personal ledger / Actual banking" title={`Good morning, ${user.firstName}`} detail="Connect a bank to activate your real financial workspace." /><ConnectBankState user={user} /></div>;
  }
  const balance = accounts.reduce((sum, account) => sum + account.currentBalance, 0);
  return <div className="ledger-page"><SectionTitle eyebrow="Personal ledger / September 2026" title={`Good morning, ${user.firstName}`} detail="Your financial position, projected forward." /><div className="ledger-kpi-grid"><div className="ledger-kpi ledger-kpi-primary"><p>Net position</p><strong><Money value={balance} /></strong><span>↑ 4.8% from last month</span></div><div className="ledger-kpi"><p>Available cash</p><strong><Money value={balance - 800} /></strong><span>Across {accounts.length} accounts</span></div><div className="ledger-kpi"><p>Next recurring outflow</p><strong><Money value={1750} /></strong><span>Apartment Rent · in 18 days</span></div><div className="ledger-kpi"><p>Attention needed</p><strong>2 <small>items</small></strong><span className="ledger-flag-text">Review before Friday</span></div></div><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel ledger-panel-chart"><div className="panel-heading"><div><p className="ledger-eyebrow">Cash flow</p><h2>Forecast through October 31</h2></div><span className="simulated-tag">SIMULATED FORECAST</span></div><ForecastChart /></section><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Outgoings</p><h2>Spending by category</h2></div><a className="ledger-icon-button" aria-label="View insights" href="/root/insights"><ChevronRight size={18} /></a></div><CategoryDonut /></section></div><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Recent activity</p><h2>Latest entries</h2></div><a className="ledger-text-link" href="/root/accounts">View all <ChevronRight size={14} /></a></div><ActivityList transactions={transactions} /></section><section className="ledger-panel attention-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Review queue</p><h2>Flagged for your attention</h2></div><ShieldAlert size={20} className="ledger-flag-text" /></div><div className="attention-item"><div><strong>Apartment Rent</strong><p>3x median transaction size</p></div><span className="attention-pill">Review</span></div><div className="attention-item"><div><strong>Railway Market</strong><p>First-time payee · $84.50</p></div><span className="attention-pill">Review</span></div><a className="ledger-text-link mt-5" href="/root/operations">Open operations queue <ChevronRight size={14} /></a></section></div></div>;
}

function TransactionsTable({ transactions }: { transactions: LedgerTransaction[] }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All");
  const filtered = transactions.filter((item) => `${item.merchant} ${item.category}`.toLowerCase().includes(query.toLowerCase()) && (category === "All" || item.category === category));
  const exportCsv = () => { const csv = ["Date,Merchant,Category,Amount", ...filtered.map((item) => `${item.date},${item.merchant},${item.category},${item.amount}`)].join("\n"); const blob = new Blob([csv], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "nexa-transactions.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="ledger-panel"><div className="table-toolbar"><div className="ledger-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search merchant or category" /></div><select className="ledger-select" value={category} onChange={(event) => setCategory(event.target.value)}><option>All</option><option>Housing</option><option>Food & Drink</option><option>Transfer</option><option>Subscriptions</option><option>Income</option></select><button className="ledger-button secondary" onClick={exportCsv}><Download size={16} /> Export CSV</button></div><div className="ledger-table-wrap"><table className="ledger-table"><thead><tr><th>Date</th><th>Merchant</th><th>Category</th><th>Account</th><th className="text-right">Amount</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td>{item.date}</td><td><strong>{item.merchant}</strong>{item.flagged && <span className="table-flag">Flagged</span>}</td><td>{item.category}</td><td>•• {item.accountId?.slice(-4)}</td><td className={`text-right font-semibold ${item.type === "credit" ? "ledger-positive" : ""}`}><Money value={item.type === "credit" ? item.amount : -item.amount} /></td></tr>)}</tbody></table></div></div>;
}

function Accounts({ accounts, transactions, user }: { accounts: Account[]; transactions: LedgerTransaction[]; user: User }) { if (user.mode === "actual" && accounts.length === 0) return <div className="ledger-page"><SectionTitle eyebrow="Customer view / Accounts" title="Accounts & transactions" detail="Your connected accounts will appear here." /><ConnectBankState user={user} /></div>; return <div className="ledger-page"><SectionTitle eyebrow="Customer view / Accounts" title="Accounts & transactions" detail="A searchable record of every movement across your connected accounts." /><div className="account-strip">{accounts.map((account) => <div className="account-strip-item" key={account.id}><span className="account-mark">N</span><div><strong>{account.name}</strong><p>•• {account.mask} · {account.subtype}</p></div><b><Money value={account.currentBalance} /></b></div>)}</div><TransactionsTable transactions={transactions} /></div>; }

function Transfers() { const [confirmed, setConfirmed] = useState(false); const [amount, setAmount] = useState("200"); const [notice, setNotice] = useState(""); const idempotency = "nexa_demo_20260918_7F3A9C"; return <div className="ledger-page"><SectionTitle eyebrow="Customer view / Transfers" title="Move money" detail="Send a transfer now or make recurring obligations predictable." /><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><p className="ledger-eyebrow">New transfer</p><h2>Transfer details</h2><div className="form-grid"><label>From<select className="ledger-input"><option>Everyday Checking · •• 1024</option></select></label><label>To<select className="ledger-input"><option>Alex Morgan · saved beneficiary</option></select></label><label>Amount<input className="ledger-input" value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" /></label><label>When<select className="ledger-input"><option>Today</option><option>Schedule for later</option></select></label></div><button className="ledger-button primary" onClick={() => setConfirmed(true)}>Review transfer <ArrowUpRight size={16} /></button>{confirmed && <div className="confirmation-box"><div className="confirmation-icon"><Check size={16} /></div><div><strong>Transfer ready for confirmation</strong><p>Idempotency key: <code>{idempotency}</code></p><small>This key prevents double-charging if the request is retried.</small></div></div>}</section><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Saved beneficiaries</p><h2>People & accounts</h2></div><button className="ledger-button secondary" onClick={() => setNotice("Beneficiary creation is simulated in Demo Mode.")}>Add beneficiary</button></div>{["Alex Morgan", "Northstar Utilities", "Maya Chen"].map((name, index) => <div className="beneficiary-row" key={name}><span className="avatar">{name[0]}</span><div><strong>{name}</strong><p>•• {index === 0 ? "4182" : index === 1 ? "9901" : "2048"}</p></div>{index === 0 && <span className="new-tag">ADDED 2D AGO</span>}</div>)}{notice && <p className="ledger-muted mt-4 text-sm">{notice}</p>}</section></div><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Scheduled</p><h2>Recurring transfers</h2></div><button className="ledger-button secondary" onClick={() => setNotice("Schedule creation is simulated in Demo Mode.")}>Create schedule</button></div><div className="schedule-row"><div><strong>Rent transfer</strong><p>Every month · next on October 1</p></div><Money value={1750} /><span className="status-dot">Active</span></div></section></div>; }

function Insights() { const [adjustment, setAdjustment] = useState(200); const cells = [12, 21, 8, 33, 26, 12, 4, 9, 18, 11, 42, 24, 7, 16, 28, 14, 10, 35, 19, 9, 5]; return <div className="ledger-page"><SectionTitle eyebrow="Customer view / Insights" title="Patterns worth noticing" detail="Every recommendation below shows the evidence behind it." /><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Spending heatmap</p><h2>Category × day of week</h2></div><span className="ledger-muted text-xs">Darker = more spending</span></div><div className="heatmap"><div /><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span>{["Housing", "Food", "Travel"].map((category, row) => <div className="heat-row" key={category}><b>{category}</b>{cells.slice(row * 7, row * 7 + 7).map((value, index) => <i key={`${row}-${index}`} style={{ opacity: 0.2 + value / 60 }} title={`${category}: ${value} units`} />)}</div>)}</div></section><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Goals</p><h2>Sub-accounts</h2></div><button className="ledger-button secondary" onClick={() => window.alert("Goal creation is simulated in this environment.")}>New goal</button></div>{[["Trip Fund", 1275, 3000], ["Emergency Reserve", 4800, 7500], ["Home upgrades", 620, 2000]].map(([name, current, goal]) => <div className="goal-row" key={name as string}><div className="flex justify-between"><strong>{name as string}</strong><span><Money value={current as number} /> / <Money value={goal as number} /></span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${((current as number) / (goal as number)) * 100}%` }} /></div></div>)}</section></div><section className="ledger-panel scenario-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Scenario simulator <span className="simulated-tag">SIMULATED</span></p><h2>What if I add a monthly subscription?</h2></div><strong className="scenario-value">+${adjustment}/mo</strong></div><input className="scenario-slider" type="range" min="0" max="500" step="25" value={adjustment} onChange={(event) => setAdjustment(Number(event.target.value))} /><div className="scenario-scale"><span>$0</span><span>$250</span><span>$500</span></div><ForecastChart adjustment={adjustment} /><p className="ledger-muted text-sm">Reasoning: the projected line shifts down by the added monthly outflow while your recurring income stays unchanged.</p></section></div>; }

function Operations() { const [notice, setNotice] = useState(""); const cases = [["Apartment Rent", "3x median transaction size", "00:42:18", "amber"], ["Railway Market", "first-time payee", "03:18:44", "green"], ["Overseas ATM", "unusual hour · 03:12", "00:08:12", "red"]]; return <div className="ledger-page"><SectionTitle eyebrow="Operations / Review queue" title="Cases requiring a decision" detail="Explainable signals only. No opaque risk scores." /><section className="ledger-panel"><div className="table-toolbar"><div><p className="ledger-eyebrow">3 open cases</p><h2>Transaction review</h2></div><button className="ledger-button secondary" onClick={() => setNotice("Showing all open cases. Queue filtering is simulated.")}><SlidersHorizontal size={16} /> Filter queue</button></div>{notice && <p className="ledger-muted mb-3 text-sm">{notice}</p>}<div className="case-list">{cases.map(([merchant, reason, sla, tone]) => <div className="case-row" key={merchant}><span className={`sla-badge ${tone}`}><Clock3 size={14} /> {sla}</span><div className="flex-1"><strong>{merchant}</strong><p>{reason}</p></div><span className="case-amount"><Money value={merchant === "Apartment Rent" ? 1750 : merchant === "Railway Market" ? 84.5 : 420} /></span><button className="ledger-icon-button" aria-label={`Open ${merchant} case`} onClick={() => setNotice(`${merchant}: ${reason}. Case detail is shown below.`)}><ChevronRight size={18} /></button></div>)}</div></section><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><p className="ledger-eyebrow">Selected case</p><h2>Why this was flagged</h2><div className="reason-card"><ShieldAlert size={18} /><div><strong>Apartment Rent · $1,750.00</strong><p>3x median transaction size</p><small>Observed amount is 3.1× the customer’s 90-day median housing payment. Previous housing payments were $540–$610.</small></div></div><div className="reason-card"><LockKeyhole size={18} /><div><strong>Decision audit trail</strong><p>Rule: transaction.amount &gt; median(category) × 3</p><small>Generated at 09:17 UTC · evidence retained for 7 years</small></div></div></section><section className="ledger-panel"><p className="ledger-eyebrow">Customer lookup</p><h2>Read-only profile</h2><div className="lookup-box"><Search size={16} /><span>Search customer email or ID</span></div><p className="ledger-muted mt-4">Lookup results and customer data are read-only in Operations.</p></section></div></div>; }

function Admin() { const permissions = ["View customer data", "Approve transfers", "Manage users", "Export statements"]; const roles = ["Support", "Operations", "Admin"]; return <div className="ledger-page"><SectionTitle eyebrow="Administration" title="Control plane" detail="Access, dependencies, and security events in one restrained view." /><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Role permissions</p><h2>Who can do what</h2></div><span className="simulated-tag">SIMULATED ENFORCEMENT</span></div><div className="permission-grid"><div />{permissions.map((permission) => <span key={permission}>{permission}</span>)}{roles.map((role, roleIndex) => <div className="permission-row" key={role}><strong>{role}</strong>{permissions.map((permission, permissionIndex) => <label key={permission}><input type="checkbox" defaultChecked={roleIndex === 2 || permissionIndex === 0 || (roleIndex === 1 && permissionIndex === 1)} /><Check size={13} /></label>)}</div>)}</div></section><section className="ledger-panel"><p className="ledger-eyebrow">System health</p><h2>Service dependencies</h2><div className="dependency-map"><div className="dependency central">Nexa API<span>Healthy</span></div><div className="dependency dep-one">Appwrite<span>Healthy</span></div><div className="dependency dep-two">Plaid<span>Sandbox</span></div><div className="dependency dep-three">Dwolla<span>Healthy</span></div><svg viewBox="0 0 320 170"><path d="M160 78 L70 25 M160 78 L250 25 M160 92 L160 145" /></svg></div></section></div><div className="ledger-grid ledger-grid-wide"><section className="ledger-panel"><div className="panel-heading"><div><p className="ledger-eyebrow">Security events</p><h2>Latest activity</h2></div><Activity size={18} /></div>{["Role matrix updated", "New API key rotated", "MFA enrollment requested"].map((event, index) => <div className="security-row" key={event}><span>{index === 2 ? "SIMULATED" : "LIVE"}</span><div><strong>{event}</strong><p>Admin · {index + 1}h ago</p></div></div>)}</section><section className="ledger-panel"><p className="ledger-eyebrow">Feature flags</p><h2>Release controls</h2>{["Scenario simulator", "Instant transfers", "PDF statements"].map((flag, index) => <div className="flag-row" key={flag}><span><strong>{flag}</strong><small>{index === 2 ? "Simulated download" : "Gradual rollout"}</small></span><button className={`toggle ${index < 2 ? "on" : ""}`} aria-label={`Toggle ${flag}`}><i /></button></div>)}</section></div></div>; }

function UtilityView({ view }: { view: WorkspaceView }) { const titles: Record<string, [string, string]> = { statements: ["Statements", "Monthly statement archive and delivery preferences."], notifications: ["Notification center", "Choose which changes deserve your attention."], settings: ["Profile & security", "Manage personal details and account protections."], }; const [title, detail] = titles[view] || ["Workspace", "Your financial workspace."]; return <div className="ledger-page"><SectionTitle eyebrow={`Customer view / ${title}`} title={title} detail={detail} /><section className="ledger-panel utility-panel"><div className="utility-row"><div><h2>{view === "statements" ? "September 2026 statement" : view === "notifications" ? "Large transaction alerts" : "Sign-in and device security"}</h2><p>{view === "statements" ? "PDF generation is simulated in this environment." : view === "notifications" ? "Alert me when a transaction exceeds" : "MFA enrollment and device management are simulated."}</p></div><span className="simulated-tag">SIMULATED</span></div><div className="ledger-input-row"><input className="ledger-input" defaultValue={view === "notifications" ? "500" : "Ready"} /><button className="ledger-button primary" onClick={() => window.alert(view === "statements" ? "PDF generation is simulated in this environment." : "Preference saved locally for this demo.")}>{view === "statements" ? "Generate PDF" : "Save preference"}</button></div></section></div>; }

export default function LedgerWorkspace({ view, user, accounts, transactions = [] }: LedgerWorkspaceProps) {
  const [dark, setDark] = useState(false);
  const resolvedAccounts = accounts ?? (user.mode === "demo" ? fallbackAccounts : []);
  const resolvedTransactions = (transactions.length || user.mode === "actual" ? transactions : seedTransactions).map((item, index) => ({ ...seedTransactions[index % seedTransactions.length], ...item, merchant: (item as LedgerTransaction).merchant || item.name }));
  const content = view === "dashboard" ? <Dashboard accounts={resolvedAccounts} transactions={resolvedTransactions} user={user} /> : view === "accounts" ? <Accounts accounts={resolvedAccounts} transactions={resolvedTransactions} user={user} /> : view === "transfers" ? <Transfers /> : view === "insights" ? <Insights /> : view === "operations" ? <Operations /> : view === "admin" ? <Admin /> : <UtilityView view={view} />;
  return <div className={`ledger-app ${dark ? "ledger-dark" : ""}`}><aside className="ledger-side"><a href="/root" className="ledger-brand"><span>N</span><strong>Nexa</strong></a><p className="ledger-side-label">CUSTOMER VIEW</p><nav>{nav.map((item) => <a key={item.view} href={`/root/${item.view === "dashboard" ? "" : item.view}`} className={view === item.view ? "active" : ""}>{item.label}</a>)}</nav><p className="ledger-side-label mt-8">CONTROL ROOM</p><nav><a href="/root/operations" className={view === "operations" ? "active" : ""}>Operations queue</a><a href="/root/admin" className={view === "admin" ? "active" : ""}>Admin</a></nav><div className="ledger-side-footer"><span className="avatar">{user.firstName?.[0] || "N"}</span><div><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></div><button onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun size={16} /> : <Moon size={16} />}</button></div></aside><main className="ledger-main"><div className="ledger-topbar"><span>PERSONAL FINANCE LEDGER <b>•</b> {user.mode === "demo" ? "DEMO MODE" : "ACTUAL BANKING"}</span><span className="topbar-actions"><a href="/root/select-mode" className="mode-switch-link">Switch mode</a><span className="topbar-status"><i /> All systems operational</span></span></div>{content}</main></div>;
}
